version: 2
jobs:

  pdfhtml:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip

      - run: pip install --user .[sphinx,pdfhtml]
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      - run:
          name: Install Headless Chrome dependencies
          command: |
            sudo apt-get install -yq $(cat .github/workflows/pyppeteer_reqs.txt)

      - run:
          name: Install chromium
          command: pyppeteer-install

      # Build a PDF of the book to view as an artifact
      - run:
          name: PDF from HTML
          command: jb build docs --builder pdfhtml -n -W --keep-going

      - store_artifacts:
          path: docs/_build/pdf/book.pdf
          destination: pdfhtml

  pdflatex:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - run: sudo apt-get update
      - checkout

      - restore_cache:
          keys:
            - cache-pip
      - run: pip install --user .[sphinx,pdflatex]
      - save_cache:
          key: cache-pip
          paths:
            - ~/.cache/pip

      - run:
          name: Install TeX
          command: |
            sudo apt-get install fonts-freefont-ttf
            sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-xetex

      - run:
          name: PDF from LaTeX
          command: jb build docs --builder pdflatex -n -W --keep-going

      - store_artifacts:
          path: docs/_build/latex/book.pdf
          destination: pdflatex

workflows:
  version: 2
  default:
    jobs:
      - pdfhtml
      - pdflatex
